// packages/ui-react/src/components/button.tsx
import type { Assign } from '@ark-ui/react'
import { type HTMLArkProps, ark } from '@ark-ui/react/factory'
import { ButtonVariants, buttonStyles } from '@repo/core-ui/button.css'
import * as Lucide from 'lucide-react'
import * as React from 'react'

export interface ButtonProps extends Assign<HTMLArkProps<'button'>, ButtonVariants> {
  isLoading?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ variant, size, className, isLoading, disabled, children, asChild = false, ...props }, ref) => {
    const isDisabled = disabled || isLoading
    const styles = buttonStyles({ variant, size, isLoading })

    return (
      <ark.button
        ref={ref}
        className={styles.base({ className })}
        data-loading={isLoading}
        disabled={isDisabled}
        asChild={asChild}
        {...props}
      >
        {isLoading && <Lucide.Loader2 strokeWidth={2} />}
        {children}
      </ark.button>
    )
  }
)

Button.displayName = 'Button'

export { Button }

// packages/ui-solid/src/components/button.tsx
import type { Assign } from '@ark-ui/solid'
import { type HTMLArkProps, ark } from '@ark-ui/solid/factory'
import { type ButtonVariants, buttonStyles } from '@repo/core-ui/button.css'
import * as Lucide from 'lucide-solid'
import { type Component, splitProps } from 'solid-js'

export interface ButtonProps extends Assign<HTMLArkProps<'button'>, ButtonVariants> {}

const Button: Component<ButtonProps> = (props) => {
  const [local, others] = splitProps(props, [
    'variant',
    'size',
    'class',
    'isLoading',
    'disabled',
    'children',
    'asChild',
  ])

  const isDisabled = () => local.disabled || local.isLoading
  const styles = buttonStyles({
    variant: local.variant,
    size: local.size,
    isLoading: local.isLoading,
  })

  return (
    <ark.button
      class={styles.base({ className: local.class })}
      data-loading={local.isLoading}
      disabled={isDisabled()}
      asChild={local.asChild}
      {...others}
    >
      {local.isLoading && <Lucide.Loader2 strokeWidth={2} />}
      {local.children}
    </ark.button>
  )
}

export { Button }
