// apps/docs-solid/src/main.tsx
/* @refresh reload */
import { render } from 'solid-js/web'
import App from './app'

// Import the Tailwind CSS styles.
import '@repo/core-ui/tailwind.css'
import './main.css'

// The root element for the app.
const rootElement = document.getElementById('app')

if (!rootElement) {
  throw new Error(
    "Root element not found. Check if it's in your index.html or if the id is correct."
  )
}

render(() => <App />, rootElement)

// apps/docs-react/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './app'

// Import the Tailwind CSS styles.
import '@repo/core-ui/tailwind.css'
import './main.css'

// The root element for the app.
const rootElement = document.getElementById('app')

if (!rootElement) {
  throw new Error(
    "Root element not found. Check if it's in your index.html or if the id is correct."
  )
}

// When you use Strict Mode, React renders each component twice to help you find unexpected side effects.
// @ref: https://react.dev/blog/2022/03/08/react-18-upgrade-guide#react
ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
